# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  playitforward.lunar.build:
    site_hosts:
      - canonical: playitforward.lunar.build
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:Harry-Gardiner/Play-it-forward.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: develop
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    xmlrpc:
      enabled: false
    nginx_embed_security: false
    deploy_keep_releases: 3
